auth:
  type: DISABLED

kafka:
  gravitee:
    managementApiUrl: http://localhost:8083/management/v2/organizations/DEFAULT/environments/DEFAULT
    managementApiOrgAdminUsername: admin
    managementApiOrgAdminPassword: admin
#  clusters:
#    - name: local
#      bootstrapServers: myapi.kafka.local:9092
#      ssl:
#        truststore-location: ~/Gravitee/kafka-tests/docker/config/ssl/server.truststore.jks
#        truststore-password: gravitee
#    - name: direct
#      bootstrapServers: localhost:9091

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"

logging:
  level:
    root: INFO
    io.kafbat.ui: DEBUG
    reactor.netty.http.server.AccessLog: INFO
    org.hibernate.validator: WARN

